Adding tests
DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi pull request #24
Opened 2022-09-14 19:11 UTC by princessmittens

Adding unit tests for S104/S111 output files.

Currently this contains a test session that creates a hardcoded curl request and returns the s104/s111 file. 

Files include:
test_s111_output.py - Main testing script for s111 request/tests
test_s104_output.py - Main testing script for s104 request/tests
test_util.py - general script used by `test_s104_output.py` and `test_s111_output.py` files
test_data.py - hardcoded data fields for attributes, attribute types and dataset types

2022-09-15 16:32 UTC, maximecarre1 requested changes
tests/.#README.md should be  deleted from the repo and added to gitignore, everything else looks good.

2022-09-15 16:32 UTC, maximecarre1 commented on tests/.#README.md
> +CHRISTIANSA@WLNSBIO9060661.18864:1662983367
This file should be added to gitignore, just in case there is any security issues with having your workstation id exposed on the public repo

2022-09-15 16:39 UTC, maximecarre1 commented
This is out of scope for this PR, but it would be nice for a future improvement to have a script that runs the tests in S-111 Annex D and output the results to a log file or a sqlite database; if we ever need to keep a record that the files we produce pass the conformance tests described in the spec.

This is mandated in the spec for S-57 electronic charts, I don't know if it  is going to be be a future requirement for S-111/S-104 but it would be nice to have the capability to do it.

2022-09-16 12:36 UTC, princessmittens commented
Definitely, perhaps we can make an issue to address this in the future?

2022-09-20 14:42 UTC, merged