Enav version - move S104/S111 logic into S100 class
DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi pull request #8
Opened 2022-08-18 18:44 UTC by princessmittens

* Added types to params in S104, S100 and S111 classes
* Added _populate_group_metadata function in S100 
* Added _create_positioning_group function in S100
* Moved logic for _update_feature_metadata into S100 class 
* Expanded on init functions in S111/S104 to have hardcoded values that are custom to each class (passed into S100 constructor)

Note that there is a descrepancy between my branch and the eastBoundLatitude, could you take a look at this? I'm not sure why this is the case but I thought maybe you pushed a fix for it while I was working on the branch.

2022-08-18 20:01 UTC, princessmittens commented
No, I don't think it's a thing in github. Different I guess!

2022-08-18 20:40 UTC, glmcr commented
> No, I don't think it's a thing in github. Different I guess!

Not sure but I think that we have to use the "convert to draft" button for getting the same gitlab "WIP" thing effect

2022-08-25 16:09 UTC, maximecarre1 requested changes
Print statements (new and old) are causing problems when generating the open api yml file, they should be changed to generate entries in the log file.

2022-08-26 13:40 UTC, princessmittens commented on config.yml
> +Expires: 2022-08-19 18:50:30.023402
I have made the changes, can confirm this is correct? Thanks!

2022-08-26 15:02 UTC, maximecarre1 commented on config.yml
> +Expires: 2022-08-19 18:50:30.023402
Yes, everything looks fine for now. We are going to replace the config file later anyway to deal with [issue 11 ](https://github.com/DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi/issues/11)

2022-08-29 11:50 UTC, princessmittens commented
I think this is ready to merge if the changes have been reviewed?

2022-08-29 15:21 UTC, merged